package com.alexk.bidit.common.util.value

const val HOME_BANNER_POSITION = "HOME_BANNER_POSITION"
const val ITEM_ID = "ITEM_ID"
const val ITEM_CATEGORY_TYPE = "ITEM_CATEGORY_TYPE"
const val CATEGORY_ID = "CATEGORY_ID"
const val ITEM_IMG_URL = "ITEM_IMG_URL"
const val BID_PRICE = "BID_PRICE"
const val CURRENT_BID_PRICE = "CURRENT_BID_PRICE"
const val SELLING_ITEM_CATEGORY_IDX = "SELLING_ITEM_CATEGORY_IDX"
const val SELLING_ITEM_CATEGORY_LISTENER_KEY = "SELLING_ITEM_CATEGORY_LISTENER_KEY"